services:
  api:
    command: npm run start:dev
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  web-admin:
    build:
      context: ./web-admin
      dockerfile: Dockerfile.dev
    command: npm run dev -- --host
    volumes:
      - ./web-admin:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
